server:
  port: 8090
  servlet:
    context-path: /v1/baseinfo
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

management:
  endpoints:
    web:
      exposure:
        include: metrics,httptrace
fdfs:
  so-timeout: 3000
  connect-timeout: 1000
  thumb-image:
    width: 60
    height: 60
  tracker-list:
    - 10.10.41.3:22122
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  ## quartz定时任务,采用数据库方式
  quartz:
    job-store-type: jdbc
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: PdBaseScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  #json 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true
  #配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    prefer-file-system-access: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      #数据监控
      stat-view-servlet:
        #开启数据监控
        enabled: true
        #监控页面的登录用户名
        loginUsername: admin
        #监控页面的登录密码
        loginPassword: 123456
        deny:
        allow:
      #采集web-jdbc关联监控的数据
      web-stat-filter:
        enabled: true
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          url: jdbc:mysql://10.10.41.3:3306/workbook?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
          username: u_admin
          password: workbook2021*&^
          driver-class-name: com.mysql.cj.jdbc.Driver
  #redis 配置
  redis:
    database: 0
    host: redis-service
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: 123456
    port: 6379
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/bewg/pd/baseinfo/modules/**/xml/*Mapper.xml,classpath*:com/bewg/pd/common/**/mapper/xml/*Mapper.xml
  #configuration:
  # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
workbook:
  path:
    #文件上传根目录 设置
    upload: /opt/upload
    #webapp文件路径
    webapp: /opt/webapp
  log:
    #日志文件地址,需要地址存在
    #path: /home/applogs/workbook
    path: pd-apps
    #日志文件名称
    name: pd-baseinfo
    #日志文件最大保留天数
    max-history: 30
    #日志文件最大的大小
    max-file-size: 10MB
    #    level: error
    level: info
  login:
    kick-out-enable: false
    #token过期时间（单位：分钟）
    token-expire-time: 72000
  # 阿里云oss配置
  aliyun:
    oss:
      endpoint: oss-cn-chengdu.aliyuncs.com
      accessKeyId: accessKeyId
      accessKeySecret: accessKeySecret
      bucketName: luoyufeng
  projectinfo:
    projectid: ${projectid:BEWG_workbook_10001}