spring:
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 30MB
      # 一次请求总上传的数据大小
      max-request-size: 30MB
      # 上传文件时的临时目录, 需要长久存在
      location: /opt/upload/pd-workbook/
  redis:
    # Redis默认情况下有16个分片, 这里配置具体使用的分, 默认是0
    database: 0
    host: redis-service
    password: 123456
    port: 6379
    # 连接超时时间, 单位是毫秒(10秒)
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池中的最大空闲连接
        max-idle: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最小空闲连接（使用0表示没有限制）
        min-idle: 0

# 自定义日志目录(不配置默认为当前目录)
logging:
  file:
    path: /opt/log/pd-workbook/
    name: pd-workbook

# 计算书相关配置
workbook:
  contextDir: /opt/context