spring:
  servlet:
    context-path: /v1/workbook
  redis:
    # Redis默认情况下有16个分片, 这里配置具体使用的分, 默认是0
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    # 连接超时时间, 单位是毫秒(10秒)
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池中的最大空闲连接
        max-idle: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最小空闲连接（使用0表示没有限制）
        min-idle: 0

# 自定义日志目录(不配置默认为当前目录)
logging:
  file:
    path: /Users/siyuan926/work/document/download
    name: pd-workbook

# 计算书相关配置
workbook:
  contextDir: /Users/glen/Downloads/context
